FROM node:22-alpine

RUN apk add --no-cache libc6-compat
WORKDIR /app

RUN npm install -g pnpm@10.25.0

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY convex ./convex
COPY lib ./lib
COPY docker/scripts/migration.sh ./migration.sh

CMD ["./migration.sh"]