FROM node:22-alpine

RUN apk add --no-cache libc6-compat
WORKDIR /app

RUN npm install -g pnpm@10.25.0

COPY docker/migration/package.json docker/migration/pnpm-lock.yaml ./
RUN pnpm install --prod --frozen-lockfile

COPY convex ./convex
COPY src/lib/jtiStore.ts ./src/lib/jtiStore.ts
COPY docker/scripts/migration.sh ./migration.sh

CMD ["./migration.sh"]
