name: Build and push Docker image

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*" # spustí se i při pushnutí verze

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest

    env:
      IMAGE_NAME: rustdesk-server-webui
      REGISTRY: git.ondomain.org
      REPO_OWNER: KiskaLE

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Gitea registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REPO_OWNER }}
          password: ${{ secrets.REPO_OWNER_PASSWORD }}

      - name: Set image tags
        id: vars
        run: |
          if [[ "${GITEA_REF_TYPE}" == "tag" ]]; then
            VERSION_TAG="${GITEA_REF_NAME}"
          else
            SHORT_SHA=$(echo "${GITEA_SHA}" | cut -c1-7)
            VERSION_TAG="${GITEA_REF_NAME}-${SHORT_SHA}"
          fi
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./web
          file: ./web/Dockerfile
          target: production
          push: true
          tags: |
            ${{ env.REGISTRY }}/kiskale/${{ env.IMAGE_NAME }}:${{ env.VERSION_TAG }}
            ${{ env.REGISTRY }}/kiskale/${{ env.IMAGE_NAME }}:latest
