name: Lint and Build on push

on:
  pull_request:
    types: ["opened", "synchronize", "reopened"]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24.2.0"

      - name: Install dependencies
        run: cd ./web && npm install

      - name: Run ESLint lint
        run: cd ./web && npm run lint

      - name: Run build
        run: cd ./web && npm run build
