services:
  app:
    image: git.ondomain.org/kiskale/rustdesk-server-webui:latest
    build:
      context: ./
      target: production
      dockerfile: Dockerfile
    ports:
      - "${DOCKER_PORT:-3000}:3000"
    env_file:
      - ./.env
